### ISSUE TITLE
Bug: `tool-scope.js` missing from published npm package (0.15.1, 0.15.2)

### ISSUE THREAD

**Issue by iefnaf** [backnotprop/plannotator#391]
## Bug: `tool-scope.js` missing from published npm package

**Affected versions:** 0.15.1, 0.15.2 (and possibly earlier)

### What happens

After installing the extension via `pi install npm:@plannotator/pi-extension`, pi fails to load it with:

```
Failed to load extension "/opt/homebrew/lib/node_modules/@plannotator/pi-extension": Failed to load extension: Cannot find module './tool-scope.js'
Require stack:
- /opt/homebrew/lib/node_modules/@plannotator/pi-extension/index.ts
```

### Root cause

`index.ts` imports from `./tool-scope.js`:

```ts
import {
    getToolsForPhase,
    PLAN_SUBMIT_TOOL,
    type Phase,
    stripPlanningOnlyTools,
} from "./tool-scope.js";
```

But `tool-scope.ts` is not listed in the `files` field of `package.json`, so it is excluded from the published package. The installed directory only contains:

```
generated/
server/
index.ts
server.ts
package.json
plannotator.html
review-editor.html
README.md
```

### Fix

Add `tool-scope.ts` to the `files` array in `package.json`:

```json
"files": [
    "index.ts",
    "tool-scope.ts",
    "server.ts",
    "server/",
    "generated/",
    ...
]
```

Then republish.

**Comment by gwynnnplaine** [comment]
Same issue. Pi version: 0.62.0 with updated `pi install npm:@plannotator/pi-extension`

**Comment by marandaneto** [comment]
works on the latest 0.14.x

**Comment by backnotprop** [comment]
Sorry, not sure how this happened, my local tests all passed and it runs for me.

Deploying the patch release

**Comment by backnotprop** [comment]
Please try the patch release `@plannotator/pi-extension@0.15.3`

I will keep issue open until resolved.

**Comment by backnotprop** [comment]
Fixed in @plannotator/pi-extension@0.15.3 — `tool-scope.ts` is now included in the published package.

**Comment by gwynnnplaine** [comment]
Thank you! No more error for me :)
